config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/residential'
  get 'welcome/passive_house'
  get 'welcome/studio'
  get 'welcome/workshop'
  get 'welcome/about'

end

app/models/project.rb
class Project
  include Mongoid::Document

  field :title, type: String
  field :description, type: String
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def setup_page(type)
    
    @image_path = type
    
    params['image_num'] ? @image_num = params['image_num'] : @image_num = 0
    
    @image_array = get_images("app/assets/images/#{@image_path}/#{@item}").sort
    @thumbnail_array = get_images("app/assets/images/#{@image_path}/#{@item}/thumbnails").sort
    
    @projects = Project.where(:type => type).sort
    @selected_project = Project.where(:_id => @item).first
    @big_image_loc = "#{@image_path}/#{@item}/#{@image_array[@image_num.to_i]}"
    
  end
  
  
  def get_images(loc)
    arr = []
    Dir.foreach(loc) do |item|
      next if item == '.' or item == '..' or item == 'thumbnails'
      arr << item 
    end
    return arr
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
  
  def residential
    
    params['item'] ? @item = params['item'] : @item = 'redwood_kitchen'

    setup_page('residential') 
    
  end
  
  def passive_house
    @image_path = 'passive_house'
    
    params['item'] ? @item = params['item'] : @item = 'passive_house'
    
  end
  
  def studio
    params['item'] ? @item = params['item'] : @item = 'network_house'
    setup_page('studio')
  end
  
  def workshop
    params['item'] ? @item = params['item'] : @item = 'lampshade'
    setup_page('workshop')
  end
  
  def about
    
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tektive Design</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</div>

<div class='copyright'>
	&copy; 2014 Tektive Design
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-11345900-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>

app/views/shared/_thumbnails.html.erb
<div class='thumbnails_area'>
	
	<% 
	i = 0
    thumb_str = ""
    @thumbnail_array.each do |t| 
  		i == @image_num.to_i ? classes = "thumbnail selected_thumbnail" : classes = 'thumbnail'
  		image_link = "#{@image_path}/#{@item}/#{@image_array[i]}"
		image_src = "#{@image_path}/#{@item}/thumbnails/#{t}"
	%>
		<%= link_to("#{@image_path}?item=#{@item}&image_num=#{i}") do %>
			<%= image_tag image_src, :class => classes %>
		<% end %>
		<% i += 1 %>
  	<% end %>
</div>

app/views/welcome/about.html.erb
<div class='outer_container'>
	<div class='side_nav'>
		<div class='title'>
			<br>
			<a href='/'>TEKTIVE<br>
			DESIGN</a>
		</div>
		<ul class='links'>
			<li><a href='residential' class='nav_link'>Residential</a>
			<li><a href='passive_house' class='nav_link'>Passive House</a>
			<li><a href='studio' class='nav_link'>Studio</a>
			<li><a href='workshop' class='nav_link'>Workshop</a>
			<li><a href='about' class='active_nav_link'>About</a>						
		</ul>
		<%= image_tag 'about/contact.jpg' %>
	</div>
	
	<div class='ph_description'>	
	
			
			<p class='description_text'>
				Tektive Design is a Northern California based consulting firm focused on
				sustainable residential design.  The philosophy is to engage the aspirations
				of a client and the spirit of a place as catalysts for performative design
				that intensifies the connections of a home\'s inhabitants with each other,
				their community, and the surrounding ecosystem.   
				<br>
				Pearl Renaker worked in the high-tech software industry as a product
				manager at Google for several years and recently switched careers to
				pursue her passion for design.  She holds a B.S. in computer science
				from Yale University,  an MBA from Stanford, and a Master of Architecture
				degree from the California College of the Arts.
				<br>
				Pearl is a Certified Passive House Consultant and LEED AP.
			</p>
		</div>
		
		
	<div class='big_image'>	
		<%= image_tag 'about/pearl.jpg', :class => 'about_content_img' %>			
	</div>

app/views/welcome/index.html.erb
<div class='index_outer'>
	<div class='content'>
		<div class='top_nav'>
			<div class='title'>
				<br>
				<a href='/'>TEKTIVE
				DESIGN</a>
			</div>
			<ul class='links'>
				<li><%= link_to "Residential", welcome_residential_path %>
				<li><%= link_to "Passive House", welcome_passive_house_path %>
				<li><%= link_to "Studio", welcome_studio_path %>
				<li><%= link_to "Workshop", welcome_workshop_path %>		
				<li><%= link_to "About", welcome_about_path %>
										
			</ul>
		</div>	
		
		<div class='lampshade'>
			<img src='assets/workshop/lampshade_lg.jpg'>
		</div>
		
		<div class='footer'>
		</div>
	</div>
</div>

app/views/welcome/passive_house.html.erb
<div class='outer_container'>
	<div class='side_nav'>
		<div class='title'>
			<br>
			<a href='/'>TEKTIVE<br>
			DESIGN</a>
		</div>
		<ul class='links'>
			<li><a href='residential' class='nav_link'>Residential</a>


			<li><a href='passive_house' class='active_nav_link'>Passive House</a>
	

			<li><a href='studio' class='nav_link'>Studio</a>
			<li><a href='workshop' class='nav_link'>Workshop</a>
			<li><a href='about' class='nav_link'>About</a>						
		</ul>
	</div>
	
	<div class='ph_description'>	
	
			
			<p class='description_text'>
				Passive House is an energy performance standard
				and systematic approach for designing energy-
				efficient houses.  Demand for heating and cooling
				energy is reduced by up to 90% compared
				to typical construction, while the indoor air
				quality and comfort of the inhabitants is improved.
				<br>
				The Passive House approach starts with a
				well insulated, tightly sealed building envelope. 
				An energy recovery ventilator provides a
				constant flow of fresh air into the house while
				capturing and reusing heat energy (or cooling
				energy in the summer).   Carefully planned
				solar gains warm the house in the winter
				while shading elements shield the house in
				the summer.  The comfort and durability of
				the house are improved as cold windows,
				drafts, and leaks causing condensation and
				mold growth are eliminated.
				<br>
				Buildings in the United States annually
				consume 39% of the country's energy use
				and 68% of its electricity.  Decisions made
				in new construction today have impacts
				lasting for 20, 50, 100 or more years.
				<br>
				Building a new home or remodeling an
				existing home is an ideal opportunity to
				increase energy efficiency and reduce your
				environmental impact.
				<br>
				For more information:
				<ul class="ph_ul">
					<li class="ph_li"><a href="http://www.passivehouse.us">Passive House Institute U.S.</a>
					<li class="ph_li"><a href="http://www.passivehouseca.org">Passive House California</a>
					<li class="ph_li"><a href="http://www.nytimes.com/2010/09/26/business/energy-environment/26smart.html">New York Times article:  "A Brighter Shade of Green"</a>
				</ul>
			</p>
		</div>
		
		
	<div class='ph_big_image'>	
		<%= image_tag 'passive_house/ph.jpg', :class => 'ph_content_img' %>			
	</div>

app/views/welcome/residential.html.erb
<div class='outer_container'>
	<div class='side_nav'>
		<div class='title'>
			<br>
			<a href='/'>TEKTIVE<br>
			DESIGN</a>
		</div>
		<ul class='links'>
			<li><a href='residential' class='nav_link'>Residential</a>
				<ul class='subnav'>
					<% @projects.each do |p| %>
						<% p._id == @item ? nav_class = 'selected_sub_nav' : nav_class = 'sub_nav_link' %>
						<li class = <%= nav_class %> ><%= link_to p.title, "residential?item=#{p._id}" %>
					
					<% end %>
				</ul>

			<li><a href='passive_house' class='nav_link'>Passive House</a>
			<li><a href='studio' class='nav_link'>Studio</a>
			<li><a href='workshop' class='nav_link'>Workshop</a>
			<li><a href='about' class='nav_link'>About</a>						
		</ul>
		<div class='description'>
			<h3 class='description_title'><%= @selected_project.title %></h3>
			<p class='description_text'>
				<%= raw CGI.unescapeHTML(@selected_project.description) %>
				
			</p>
		</div>
	</div>	
	
	<%= render "shared/thumbnails" %>
	
	<div class='big_image'>	
		<%= image_tag @big_image_loc, :class => 'content_img' %>			
	</div>

app/views/welcome/studio.html.erb
<div class='outer_container'>
	<div class='side_nav'>
		<div class='title'>
			<br>
			<a href='/'>TEKTIVE<br>
			DESIGN</a>
		</div>
		<ul class='links'>
			<li><a href='residential' class='nav_link'>Residential</a>
			<li><a href='passive_house' class='nav_link'>Passive House</a>
			<li><a href='studio' class='nav_link'>Studio</a>
				<ul class='subnav'>
					<% @projects.each do |p| %>
						<% p._id == @item ? nav_class = 'selected_sub_nav' : nav_class = 'sub_nav_link' %>
						<li class = <%= nav_class %> ><%= link_to p.title, "studio?item=#{p._id}" %>
					
					<% end %>
				</ul>
				
			<li><a href='workshop' class='nav_link'>Workshop</a>
			<li><a href='about' class='nav_link'>About</a>						
		</ul>
		<div class='description'>
			<h3 class='description_title'><%= @selected_project.title %></h3>
			<p class='description_text'>
				<%= raw CGI.unescapeHTML(@selected_project.description) %>
				
			</p>
		</div>
	</div>	
	
	<%= render "shared/thumbnails" %>
	
	<div class='big_image'>	
		<%= image_tag @big_image_loc, :class => 'content_img' %>			
	</div>

app/views/welcome/workshop.html.erb
<div class='outer_container'>
	<div class='side_nav'>
		<div class='title'>
			<br>
			<a href='/'>TEKTIVE<br>
			DESIGN</a>
		</div>
		<ul class='links'>
			<li><a href='residential' class='nav_link'>Residential</a>
			<li><a href='passive_house' class='nav_link'>Passive House</a>
			<li><a href='studio' class='nav_link'>Studio</a>

			<li><a href='workshop' class='nav_link'>Workshop</a>
				<ul class='subnav'>
					<% @projects.each do |p| %>
						<% p._id == @item ? nav_class = 'selected_sub_nav' : nav_class = 'sub_nav_link' %>
						<li class = <%= nav_class %> ><%= link_to p.title, "workshop?item=#{p._id}" %>
					
					<% end %>
				</ul>

			<li><a href='about' class='nav_link'>About</a>						
		</ul>
		<div class='description'>
			<h3 class='description_title'><%= @selected_project.title %></h3>
			<p class='description_text'>
				<%= raw CGI.unescapeHTML(@selected_project.description) %>
				
			</p>
		</div>
	</div>	
	
	<%= render "shared/thumbnails" %>
	
	<div class='big_image'>	
		<%= image_tag @big_image_loc, :class => 'content_img' %>			
	</div>